eduapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blog', views.blog, name='blog'),
    path('material', views.material, name='material'),
    path('material/ai',views.ai,name='material_ai'),
    path('material/cse',views.cse,name='material_cse'),
    path('material/ece',views.ece,name='material_ece'),
    path('material/mech',views.mech,name='material_mech'),
    path('material/it',views.it,name='material_it'),
    path('blog/<int:blog_id>',views.blog_detail,name='blog_detail'),
]

edubase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eduapp.urls')),
    path('summernote/', include('django_summernote.urls'))
]
admin.site.site_header = 'EduBase'
admin.site.site_title = 'EduBase'
admin.site.index_title = 'Admin Panel'

eduapp/models.py
from django.db import models
from django_summernote.fields import SummernoteTextField
from django.contrib.auth.models import User


# Create your models here.
class image(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')


class AI_Subject(models.Model):
    subject_name = models.CharField(max_length=100)

    def __str__(self):
        return self.subject_name

    class Meta:
        verbose_name = "Subject"
        verbose_name_plural = "AI"


class ai_note(models.Model):
    subject = models.ForeignKey(AI_Subject, on_delete=models.CASCADE)
    note_name = models.CharField(max_length=100)
    file = models.FileField(upload_to='ai_materials/')


class CSE_Subject(models.Model):
    subject_name = models.CharField(max_length=100)

    def __str__(self):
        return self.subject_name

    class Meta:
        verbose_name = "Subject"
        verbose_name_plural = "CSE"


class cse_note(models.Model):
    subject = models.ForeignKey(CSE_Subject, on_delete=models.CASCADE)
    note_name = models.CharField(max_length=100)
    file = models.FileField(upload_to='cse_materials/')


class IT_Subject(models.Model):
    subject_name = models.CharField(max_length=100)

    def __str__(self):
        return self.subject_name

    class Meta:
        verbose_name = "Subject"
        verbose_name_plural = "IT"


class it_note(models.Model):
    subject = models.ForeignKey(IT_Subject, on_delete=models.CASCADE)
    note_name = models.CharField(max_length=100)
    file = models.FileField(upload_to='it_materials/')


class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    image_template = models.ImageField(upload_to='blog_template_pics/', default='')
    template_desc = models.TextField(default='')
    tag = models.CharField(max_length=30)
    date_posted = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Blog Post"
        verbose_name_plural = "Blog"

eduapp/views.py
import os
from django.shortcuts import render
from .models import AI_Subject,IT_Subject,CSE_Subject,BlogPost
from django.core.paginator import Paginator
from django.conf import settings


# Create your views here.
def index(request):
    return render(request, 'eduapp/index.html')


def blog(request):
    blogs = BlogPost.objects.all()
    paginator = Paginator(blogs, 2)
    page_number = request.GET.get('blog_page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'eduapp/blog.html' , {'page_obj': page_obj})


def material(request):
    return render(request, 'eduapp/material.html')


def ai(request):
    ai_subjects = AI_Subject.objects.all()
    return render(request, 'eduapp/ai.html', {'ai_subjects': ai_subjects,'base_url':settings.MEDIA_URL})


def cse(request):
    cse_subjects = CSE_Subject.objects.all()
    return render(request, 'eduapp/cse.html',{'cse_subjects': cse_subjects,'base_url':settings.MEDIA_URL})


def ece(request):
    return render(request, 'eduapp/ece.html')


def mech(request):
    return render(request, 'eduapp/mech.html')

def it(request):
    it_subjects = IT_Subject.objects.all()
    return render(request, 'eduapp/it.html',{'it_subjects': it_subjects})

def blog_detail(request,blog_id):
    curr_blog = BlogPost.objects.get(id=blog_id)
    return render(request, 'eduapp/blog_detail.html', {'blog': curr_blog})

eduapp/templates/eduapp/ai.html
{% extends 'eduapp/base.html' %}
{% load static %}
{% block material_active %}
    active
{% endblock %}
{% block content %}
    <section class="page-section portfolio" id="portfolio">
        <br>
        <br>
        <br>
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">SYLLABUS</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                <a class="btn btn-warning" href="" target="_blank" role="button"> SEM - 1 </a>
                <a class="btn btn-warning" href="" target="_blank" role="button"> SEM - 2 </a>
                <a class="btn btn-warning" href="" target="_blank" role="button"> SEM - 3 </a>
                <a class="btn btn-warning" href="" target="_blank" role="button"> SEM - 4 </a>
            </div>
        </div>
        <br>
        <hr>
        <br>
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">DIGITAL MATERIAL</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="accordion accordion-flush" id="accordionFlushExample">
                {% for subject in ai_subjects %}
                    <div class="accordion-item text-center">
                        <h2 class="accordion-header" id="flush-heading{{ forloop.counter }}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#flush-collapse{{ forloop.counter }}" aria-expanded="false"
                                    aria-controls="flush-collapse{{ forloop.counter }}">
                                {{ subject.subject_name }}
                            </button>
                        </h2>
                        <div id="flush-collapse{{ forloop.counter }}" class="accordion-collapse collapse"
                             aria-labelledby="flush-heading{{ forloop.counter }}"
                             data-bs-parent="#accordionFlushExample">
                            <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                                {% for book in subject.ai_note_set.all %}
                                    <a class="btn btn-warning" href="{{ book.file.url }}" target="_blank" role="button">
                                        {{ book.note_name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

eduapp/templates/eduapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Edubase - Free study resources</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon"
          href="{% static 'eduapp/assets/img/portfolio/download-removebg-preview.png' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'eduapp/css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">Edu Base</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-0 mx-lg-1"><a
                        class="nav-link py-3 px-0 px-lg-3 rounded  {% block home_active %}{% endblock %}"
                        href="{% url 'index' %}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a
                        class="nav-link py-3 px-0 px-lg-3 rounded {% block material_active %}{% endblock %}" href="{% url 'material' %}">Material</a>
                </li>
                <li class="nav-item mx-0 mx-lg-1"><a
                        class="nav-link py-3 px-0 px-lg-3 rounded {% block blog_active %}{% endblock %}"
                        href="{% url 'blog' %}">Blog</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}

{% endblock %}
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <!-- Footer Location-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Location</h4>
                <p class="lead mb-0">
                    Chennai, Tamil Nadu
                    <br/>
                    Dalal Street , MO 65243
                </p>
            </div>
            <!-- Footer Social Icons-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Around the Web</h4>
                <a class="btn btn-outline-light btn-social mx-1" href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" href="#"><i class="fab fa-fw fa-twitter"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" href="#"><i class="fab fa-fw fa-linkedin-in"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" href="#"><i class="fab fa-fw fa-instagram"></i></a>
            </div>
            <!-- Footer About Text-->
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4">Contact Us</h4>
                <p class="lead mb-0">
                    Contact us at support@edubase.com
                    <!--a href="http://startbootstrap.com">HERE</a-->
                    .
                </p>
            </div>
        </div>
    </div>
</footer>
<!-- Copyright Section-->
<div class="copyright py-4 text-center text-white">
    <div class="container font-monospace"><small>Copyright &copy; All rights reserved 2022</small></div>
</div>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'eduapp/js/scripts.js' %}"></script>

<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

eduapp/templates/eduapp/blog.html
{% extends 'eduapp/base.html' %}
{% block blog_active %}
    active
{% endblock %}
{% block content %}
    <section class="page-section portfolio" id="portfolio">
        <br>
        <br>
        <div class="container">
            {% for blog_obj in page_obj %}
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ blog_obj.image_template.url }}" class="rounded-start img-thumbnail" alt="..."
                                 style="height: 15vw; width : 25vw">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ blog_obj.title }}</h5>
                                <p class="card-text">{{ blog_obj.template_desc }}</p>
                                <p class="card-text"><small class="text-muted">{{ blog_obj.date_posted }}</small></p>
                            </div>
                            <div class="text-left">
                                <a href="{% url 'blog_detail' blog_id=blog_obj.id %}">
                                    <button class="btn btn-primary">View</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <br>
        <br>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?blog_page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% endif %}
                <li class="page-item"><a class="page-link"
                                         href="?blog_page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link"
                                             href="?blog_page={{ page_obj.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
    </section>
{% endblock %}

eduapp/templates/eduapp/blog_detail.html
{% extends 'eduapp/base.html' %}
{% block blog_active %}
    active
{% endblock %}
{% block content %}
    <section class="page-section portfolio" id="portfolio">
        <br>
        <br>

            <div class="container">
                <h1 class="text-center">{{ blog.title }}</h1>
                {{ blog.content|safe }}
            </div>

        <br>
        <br>

    </section>
{% endblock %}

eduapp/templates/eduapp/cse.html
{% extends 'eduapp/base.html' %}
{% block material_active %}
active
{% endblock %}
{% block content %}
    <section class="page-section portfolio" id="portfolio">
        <br>
        <br>
        <br>
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">SYLLABUS</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                <a class="btn btn-primary" href="" target="_blank" role="button"> SEM - 1 </a>
                <a class="btn btn-primary" href="" target="_blank" role="button"> SEM - 2 </a>
                <a class="btn btn-primary" href="" target="_blank" role="button"> SEM - 3 </a>
                <a class="btn btn-primary" href="" target="_blank" role="button"> SEM - 4 </a>
            </div>
        </div>
        <br>
        <hr>
        <br>
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">DIGITAL MATERIAL</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item text-center">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseOne" aria-expanded="false"
                                aria-controls="flush-collapseOne">
                            DBMS
                        </button>
                    </h2>
                    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                         data-bs-parent="#accordionFlushExample">
                        <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 1 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 2 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 3 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 4 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> Important questions </a>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseTwo" aria-expanded="false"
                                aria-controls="flush-collapseTwo">
                            Data Analytics
                        </button>
                    </h2>

                    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo"
                         data-bs-parent="#accordionFlushExample">
                        <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 1 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 2 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 3 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 4 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> Important questions </a>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseThree" aria-expanded="false"
                                aria-controls="flush-collapseThree">
                            Operating System
                        </button>
                    </h2>
                    <div id="flush-collapseThree" class="accordion-collapse collapse"
                         aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                        <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 1 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 2 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 3 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 4 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> Important questions </a>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingFour">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapseFour" aria-expanded="false"
                                aria-controls="flush-collapseFour">
                            Maths
                        </button>
                    </h2>
                    <div id="flush-collapseFour" class="accordion-collapse collapse"
                         aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
                        <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 1 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 2 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 3 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> UNIT - 4 </a>
                            <a class="btn btn-primary" href="" target="_blank" role="button"> Important questions </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
{% endblock %}

eduapp/templates/eduapp/it.html
{% extends 'eduapp/base.html' %}
{% load static %}
{% block material_active %}
    active
{% endblock %}
{% block content %}
    <section class="page-section portfolio" id="portfolio">
        <br>
        <br>
        <br>
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">SYLLABUS</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                <a class="btn btn-warning" href="" target="_blank" role="button"> SEM - 1 </a>
                <a class="btn btn-warning" href="" target="_blank" role="button"> SEM - 2 </a>
                <a class="btn btn-warning" href="" target="_blank" role="button"> SEM - 3 </a>
                <a class="btn btn-warning" href="" target="_blank" role="button"> SEM - 4 </a>
            </div>
        </div>
        <br>
        <hr>
        <br>
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">DIGITAL MATERIAL</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="accordion accordion-flush" id="accordionFlushExample">
                {% for subject in it_subjects %}
                    <div class="accordion-item text-center">
                        <h2 class="accordion-header" id="flush-heading{{ forloop.counter }}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#flush-collapse{{ forloop.counter }}" aria-expanded="false"
                                    aria-controls="flush-collapse{{ forloop.counter }}">
                                {{ subject.subject_name }}
                            </button>
                        </h2>
                        <div id="flush-collapse{{ forloop.counter }}" class="accordion-collapse collapse"
                             aria-labelledby="flush-heading{{ forloop.counter }}"
                             data-bs-parent="#accordionFlushExample">
                            <div class="d-grid gap-2 col-6 mx-auto px-5 mt-3 mb-3">
                                {% for book in subject.ai_note_set.all %}
                                    <a class="btn btn-warning" href="{{ base_url }}{{ book.file }}" target="_blank" role="button">
                                        {{ book.note_name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

eduapp/templates/eduapp/material.html
{% extends 'eduapp/base.html' %}
{% load static %}
{% block material_active %}
    active
{% endblock %}
{% block content %}
    <!-- Department Section-->
    <section class="page-section portfolio" id="portfolio">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>

    </section>
{% endblock %}